version: '3'

services:
  db:
   image: mysql:latest
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: database
   volumes:
      - database:/var/lib/mysql  
   ports:
      - '3306:3306'
   

   networks:
      - sonarnet
  
  python:
    image: custom_python:latest
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - app:/app
    ports:
      - '5000:5000'
    networks:
      - sonarnet    

  prometheus:
     image: "prom/prometheus:v2.8.0"
     command: ["--config.file=/prometheus.yml"]
     volumes:
       - prometheus:/prometheus.yml
     ports:
       - 9090:9090
     networks:
       - sonarnet
  adapter:
    image: "redislabs/prometheus-redistimeseries-adapter:master"
    command: ["-redis-address", "redis:6379", "-web.listen-address", "0.0.0.0:9201"]
  redis:
    image: "redislabs/redistimeseries:edge"
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - sonarnet
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge     

volumes:
  database:
  redis-data:
  app:
  prometheus: